---

- name: Install httpd and start
  yum:
    name: httpd
    state: latest

- name: Customize index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart httpd service

- name: Start httpd service
  service: 
    name: httpd 
    enabled: yes 
    state: started